//Stat additions by Ben Pridham on 23/09/2026
//Debris hook on demolition added by Nho Anh Khoa Nguyen on 30/09/2026

using System.Collections.Generic;
using UnityEngine;

// generated by ChatGPT
public class Building : MonoBehaviour
{
    private readonly List<Plot> occupiedPlots = new List<Plot>();

    public IReadOnlyList<Plot> OccupiedPlots => occupiedPlots;

    public void SetOccupiedPlots(List<Plot> plots, string buildingType)
    {
        occupiedPlots.Clear();
        occupiedPlots.AddRange(plots);

        foreach (Plot plot in occupiedPlots)
        {
            if (plot != null)
                plot.Occupy(this);
        }

        GameObject.FindWithTag("GameController").GetComponent<ManagerStats>().ChangeStatByBuilding(buildingType, 1);
    }

    public void Demolish(string buildingType)
    {
        GameObject.FindWithTag("GameController").GetComponent<ManagerStats>().ChangeStatByBuilding(buildingType, -1);

        foreach (Plot plot in occupiedPlots)
        {
            if (plot != null)
                plot.ClearBuilding();
        }
        
        occupiedPlots.Clear();

        // Spawn physics debris at the building position before it disappears.
        // The building type decides which materials it breaks into.
        // Safe to call in every scene: it does nothing if no DebrisSpawner is present.
        DebrisSpawner.ExplodeAt(transform.position, buildingType);

        Destroy(gameObject);
    }
}