using UnityEngine;
using UnityEngine.SceneManagement;

// generated by ChatGPT
public class MainMenuController : MonoBehaviour
{
    [SerializeField] private GameObject mainMenuPanel;
    [SerializeField] private GameObject controlsPanel;

    private void Start()
    {
        if (mainMenuPanel != null)
            mainMenuPanel.SetActive(true);

        if (controlsPanel != null)
            controlsPanel.SetActive(false);
    }

    public void LoadStage1()
    {
        SceneManager.LoadScene("SceneLevel1");
    }

    public void LoadStage2()
    {
        SceneManager.LoadScene("SceneLevel2");
    }

    public void LoadStage3()
    {
        SceneManager.LoadScene("SceneLevel3");
    }

    public void LoadMainMenu()
    {
        SceneManager.LoadScene("SceneMainMenu");
    }

    public void ShowControls()
    {
        if (mainMenuPanel != null)
            mainMenuPanel.SetActive(false);

        if (controlsPanel != null)
            controlsPanel.SetActive(true);
    }

    public void HideControls()
    {
        if (controlsPanel != null)
            controlsPanel.SetActive(false);

        if (mainMenuPanel != null)
            mainMenuPanel.SetActive(true);
    }

    public void QuitGame()
    {
        Application.Quit();
    }
}