using UnityEngine;

// generated by ChatGPT
public class MainMenuController : MonoBehaviour
{
    [SerializeField] private GameObject mainMenuPanel;
    [SerializeField] private GameObject homeButton;
    [SerializeField] private PlayerMovement playerMovement;

    private void Start()
    {
        ShowMainMenu();
    }

    public void ShowMainMenu()
    {
        mainMenuPanel.SetActive(true);
        homeButton.SetActive(false);

        if (playerMovement != null)
        {
            playerMovement.enabled = false;
        }
    }

    public void HideMainMenu()
    {
        mainMenuPanel.SetActive(false);
        homeButton.SetActive(true);

        if (playerMovement != null)
        {
            playerMovement.enabled = true;
        }
    }
}