using UnityEngine;
using UnityEngine.InputSystem;

// generated by ChatGPT

[RequireComponent(typeof(Rigidbody2D))]
[RequireComponent(typeof(Animator))]
public class PlayerMovement : MonoBehaviour
{
    [SerializeField] private float moveSpeed = 3f;

    private Rigidbody2D rb;
    private Animator animator;

    // Surface system: reads ground modifiers without this script knowing about zones.
    private SurfaceReceiver surfaces;

    // Input-driven velocity, kept separate so external pushes stay purely additive.
    private Vector2 currentVelocity;

    private Vector2 moveDirection;

    private Vector2 facingDirection = new Vector2(1f, 1f);

    private void Awake()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
        surfaces = GetComponent<SurfaceReceiver>();
    }

    private void Update()
    {
        float x = 0f;
        float y = 0f;

        if (Keyboard.current.aKey.isPressed)
            x -= 1f;

        if (Keyboard.current.dKey.isPressed)
            x += 1f;

        if (Keyboard.current.sKey.isPressed)
            y -= 1f;

        if (Keyboard.current.wKey.isPressed)
            y += 1f;

        Vector2 input = new Vector2(x, y);

        // Actual movement: normal up/down/left/right
        moveDirection = input.normalized;

        if (input != Vector2.zero)
        {
            // Choose the closest available isometric facing animation
            if (x > 0 && y >= 0)
                facingDirection = new Vector2(1f, 1f);      // NE

            else if (x < 0 && y >= 0)
                facingDirection = new Vector2(-1f, 1f);     // NW

            else if (x > 0 && y < 0)
                facingDirection = new Vector2(1f, -1f);     // SE

            else if (x < 0 && y < 0)
                facingDirection = new Vector2(-1f, -1f);    // SW

            else if (y > 0)
                facingDirection = new Vector2(-1f, 1f);     // W -> NW

            else if (y < 0)
                facingDirection = new Vector2(1f, -1f);     // S -> SE

            animator.SetFloat("MoveX", facingDirection.x);
            animator.SetFloat("MoveY", facingDirection.y);

            animator.SetFloat("LastX", facingDirection.x);
            animator.SetFloat("LastY", facingDirection.y);
        }

        animator.SetFloat("Speed", moveDirection.sqrMagnitude);
    }

    private void FixedUpdate()
    {
        // Fall back to neutral settings if no SurfaceReceiver is attached,
        // so the player still moves normally in scenes that have no surface zones.
        SurfaceSettings surface = surfaces != null
            ? surfaces.CurrentSurface
            : SurfaceSettings.Default;

        Vector2 target =
            moveDirection
            * moveSpeed
            * surface.speedMultiplier;

        // Easing towards the target rather than snapping to it is what makes
        // surfaces with lower control feel slippery.
        // control = 1 behaves like the original movement.
        currentVelocity = Vector2.Lerp(
            currentVelocity,
            target,
            surface.control
        );

        Vector2 external = surfaces != null
            ? surfaces.ExternalVelocity
            : Vector2.zero;

        rb.linearVelocity = currentVelocity + external;
    }

    private void OnDisable()
    {
        // Important for Main Menu:
        // stop the player immediately when PlayerMovement is disabled.
        moveDirection = Vector2.zero;
        currentVelocity = Vector2.zero;

        if (rb != null)
        {
            rb.linearVelocity = Vector2.zero;
        }

        if (animator != null)
        {
            animator.SetFloat("Speed", 0f);
        }
    }
}