using UnityEngine;
using UnityEngine.InputSystem;

// generated by ChatGPT

[RequireComponent(typeof(Rigidbody2D))]
[RequireComponent(typeof(Animator))]
public class PlayerMovement : MonoBehaviour
{
    [SerializeField] private float moveSpeed = 3f;

    private Rigidbody2D rb;
    private Animator animator;
    private SurfaceReceiver surfaces;

    private Vector2 currentVelocity;
    private Vector2 moveDirection;
    private Vector2 facingDirection = new Vector2(1f, 1f);

    public Vector2 FacingDirection => facingDirection;

    private void Awake()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
        surfaces = GetComponent<SurfaceReceiver>();
    }

    private void Update()
    {
        float x = 0f;
        float y = 0f;

        if (Keyboard.current.aKey.isPressed)
            x -= 1f;

        if (Keyboard.current.dKey.isPressed)
            x += 1f;

        if (Keyboard.current.sKey.isPressed)
            y -= 1f;

        if (Keyboard.current.wKey.isPressed)
            y += 1f;

        Vector2 input = new Vector2(x, y);
        moveDirection = input.normalized;

        if (input != Vector2.zero)
        {
            if (y > 0)
                facingDirection = new Vector2(-1f, 1f);
            else if (y < 0)
                facingDirection = new Vector2(1f, -1f);
            else if (x > 0)
                facingDirection = new Vector2(1f, 1f);
            else if (x < 0)
                facingDirection = new Vector2(-1f, -1f);

            animator.SetFloat("MoveX", facingDirection.x);
            animator.SetFloat("MoveY", facingDirection.y);
            animator.SetFloat("LastX", facingDirection.x);
            animator.SetFloat("LastY", facingDirection.y);
        }

        animator.SetFloat("Speed", moveDirection.sqrMagnitude);
    }

    private void FixedUpdate()
    {
        SurfaceSettings surface = surfaces != null
            ? surfaces.CurrentSurface
            : SurfaceSettings.Default;

        Vector2 target =
            moveDirection *
            moveSpeed *
            surface.speedMultiplier;

        currentVelocity = Vector2.Lerp(
            currentVelocity,
            target,
            surface.control
        );

        Vector2 external = surfaces != null
            ? surfaces.ExternalVelocity
            : Vector2.zero;

        rb.linearVelocity = currentVelocity + external;
    }

    private void OnDisable()
    {
        moveDirection = Vector2.zero;
        currentVelocity = Vector2.zero;

        if (rb != null)
            rb.linearVelocity = Vector2.zero;

        if (animator != null)
            animator.SetFloat("Speed", 0f);
    }
}